services:
  db:
    env_file:
      - .env
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - '3000:3000'

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - '8080:80'
    depends_on:
      - server
