version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy
    depends_on:
      - server
