### Get hot posts
GET {{api}}/posts/hot

### Get feed posts
GET {{api}}/posts/for-you
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMjI1OTcwMSwiZXhwIjoxNzMyMjYwNjAxfQ.o3ZG_9YUnXQkpclgymxKV-iryXqym7ftoijWYf8kmf0

### Get post by id
GET {{api}}/posts/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMTk4NjA3NywiZXhwIjoxNzMxOTg2OTc3fQ.PHubF14jbKECpaACe5S2_wlcMIvo2DTIPcHsfYGIosc

### Create a post
POST {{api}}/posts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMTk4NjA3NywiZXhwIjoxNzMxOTg2OTc3fQ.PHubF14jbKECpaACe5S2_wlcMIvo2DTIPcHsfYGIosc
Content-Type: application/json

{
    "text": "I'm a comment to post 1"
}


### Create a post only with images
POST {{api}}/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMTk4NTA1NiwiZXhwIjoxNzMxOTg1OTU2fQ.00kWUov4JxhBedFJ-fe9nzCBFqV3tKHZFTzKXMzRFII
Content-Type: application/json

{
    "images": ["https://i.imgur.com/FmkzNI2.png", "https://i.imgur.com/NqQIwEV.png"]
}

### Delete a post
DELETE {{api}}/posts/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMTk4NTA1NiwiZXhwIjoxNzMxOTg1OTU2fQ.00kWUov4JxhBedFJ-fe9nzCBFqV3tKHZFTzKXMzRFII

### Like/unlike a post
PUT {{api}}/posts/3/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMTk4NTA1NiwiZXhwIjoxNzMxOTg1OTU2fQ.00kWUov4JxhBedFJ-fe9nzCBFqV3tKHZFTzKXMzRFII

### Get all comments of a post
GET {{api}}/posts/1/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMjE3NTUyNywiZXhwIjoxNzMyMTc2NDI3fQ.H5FU84lun-8zbOT_gASNrOA4iZ-2OTesJttpMMYXWk8

### Comment on a post
POST {{api}}/posts/67358c28f257b691e797857e/comments
Content-type: application/json

{
    "text": "Comment text"
}