### Get all posts
GET {{api}}/posts

### Get hot posts
GET {{api}}/posts/hot

### Get feed posts
GET {{api}}/posts/feed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzM1MzViYzAwZjQ0MTk2YjMyNTlmZWIiLCJpYXQiOjE3MzE3MDY3MjUsImV4cCI6MTczMTcwNzYyNX0.qRLjUJTtd0kdF58n0wCjBLQvwFLYyLnan0v7IslhIuM

### Get post by id
GET {{api}}/posts/67355658f00a56547c761123

### Create a post
POST {{api}}/posts
Content-Type: application/json

{
    "text": "Post text"
}

### Create a post without text and image
POST {{api}}/posts
Content-Type: application/json

{
    "text": "Post text"
}

### Delete a post
DELETE {{api}}/posts/67358c28f257b691e797857e

### Like/unlike a post
PUT {{api}}/posts/67358c28f257b691e797857e/like

### Get all comments of a post
GET {{api}}/posts/67358c28f257b691e797857e/comments

### Comment on a post
POST {{api}}/posts/67358c28f257b691e797857e/comments
Content-type: application/json

{
    "text": "Comment text"
}