### login user
POST {{api}}/login
Content-Type: application/json

{
  "email": "thomas@email.com",
  "password": "asd123456"
}

### login user 2
POST {{api}}/login
Content-Type: application/json

{
  "email": "joe@email.com",
  "password": "asd123456"
}

### login user with wrong username
POST {{api}}/login
Content-Type: application/json

{
  "username": "thomas1",
  "password": "asd123456"
}


### login user with wrong password
POST {{api}}/login
Content-Type: application/json

{
"username": "thomas",
"password": "asd1234567"
}

### logout user
POST {{api}}/logout
