### login user
POST {{api}}/auth/login
Content-Type: application/json

{
  "email": "thomas@email.com",
  "password": "asd123456"
}

### login user 2
POST {{api}}/auth/login
Content-Type: application/json

{
  "email": "joe@email.com",
  "password": "asd123456"
}

### Refresh token
GET {{api}}/auth/refresh-token


### login user with wrong username
POST {{api}}/auth/login
Content-Type: application/json

{
  "username": "thomas1",
  "password": "asd123456"
}


### login user with wrong password
POST {{api}}/auth/login
Content-Type: application/json

{
"username": "thomas",
"password": "asd1234567"
}

### logout user
POST {{api}}/auth/logout
