### signup user
POST {{api}}/auth/signup
Content-Type: application/json

{
  "username": "thomas",
  "email": "thomas@email.com",
  "password": "asd123456",
  "name": "Thomas Anderson"
}

### signup user 2
POST {{api}}/auth/signup
Content-Type: application/json

{
  "username": "joe",
  "email": "joe@email.com",
  "password": "asd123456",
  "name": "Joe Jonas"
}

### Signup user with invalid field using zod
POST {{api}}/auth/signup
Content-Type: application/json

{
  "username": "tom",
  "email": "hs"
}