### signup
### signup user
POST http://localhost:8000/api/users/signup
Content-Type: application/json

{
"username": "thomas",
"email": "thomas@email.com",
"password": "asd123456",
"name": "Thomas Smith"
}

### signup user 2
POST http://localhost:8000/api/users/signup
Content-Type: application/json

{
"username": "joe",
"email": "joe@email.com",
"password": "asd123456",
"name": "Joe Smith"
}