### signup user
POST {{api}}/signup
Content-Type: application/json

{
"username": "thomas",
"email": "thomas@email.com",
"password": "asd123456"
}

### signup user 2
POST {{api}}/signup
Content-Type: application/json

{
"username": "joe",
"email": "joe@email.com",
"password": "asd123456"
}

### Signup user with invalid field using zod
POST {{api}}/signup
Content-Type: application/json

{
  "username": "tom",
  "email": "hs"
}