### Follow/unfollow user
PUT {{api}}/users/follow/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMTk4MjYyMCwiZXhwIjoxNzMxOTgzNTIwfQ.JFyTXpqIopPhlq-xnAIJVjWDLrTiMS5F0VxqspmGEYU

### Update a user
PUT {{api}}/users/me/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMTk4MjYyMCwiZXhwIjoxNzMxOTgzNTIwfQ.JFyTXpqIopPhlq-xnAIJVjWDLrTiMS5F0VxqspmGEYU
Content-Type: application/json

{
  "name": "Will Smith"
}

### Get user by username
GET {{api}}/users/joe